### ISSUE TITLE
deeplearn.org is down for a few days

### ISSUE THREAD

**Issue by taoisu** [zomux/dlmonitor#10]
Hi Raphael, the deeplearn.org has been a great place for me to catch up with the latest progress of academia, thanks for the great work! It looks like the deeplearn.org is down for the last few days, I'm wondering if the fix is on the way?

**Comment by zomux** [comment]
Hi, 

The service is restored.

I was implementing a new feature to convert PDF to mobile readable format and improving the latency, might roll out in few weeks.

**Comment by taoisu** [comment]
Sounds nice! Looking forward to it.
