### ISSUE TITLE
https://deeplearn.org is not worked

### ISSUE THREAD

**Issue by sylba2050** [zomux/dlmonitor#2]
first of all, dlmoniter is Greatest project. so, I check https://deeplearn.org EVERYDAY.
but now, it is not worked. would you restart it?
thank you.

**Comment by zomux** [comment]
Ahh, Thank you for the feedback.

I mess up the things on Cloudflare when I try to add a feature that allow people to store their favorite papers using Mendeley API.

I will fix it today.

Have a nice day!


Raphael Shu
The University of Tokyo

**Comment by zomux** [comment]
The problem is fixed

**Comment by sylba2050** [comment]
Thank you so much!
